#!/bin/bash

#
# Validates commit message by following these rules http://chris.beams.io/posts/git-commit/
#

# Echo Colors
msg_color_red='\033[0;31m'
msg_color_yellow='\033[0;33m'
msg_color_none='\033[0m'


echo -en "${msg_color_yellow}Begin commit message check...${msg_color_none} \n"

i=0
while read line; do
  if [[ $line =~ ^[#].*$ ]]; then
    continue
  fi

  echo $i

  # Validate subject
  if [[ $i -eq 0 ]]; then
    if [[ ${#line} -eq 0 ]]; then
      echo -en "${msg_color_red}Commit message can not be empty${msg_color_none} \n"
      exit 1
    fi

    if [[ ${#line} -gt 50 ]]; then
      echo -en "${msg_color_red}Subject line should not exceed 50 characters${msg_color_none} \n"
      exit 1
    else
      if ! [[ $line =~ ^[A-Z].*$ ]]; then
        echo -en "${msg_color_red}Subject line has to start with an upper case letter${msg_color_none} \n"
        exit 1
      fi

      if [[ $line =~ ^(\w+)\.$ ]]; then
        echo -en "${msg_color_red}Subject should not end with a period${msg_color_none} \n"
        exit 1
      fi
    fi
  fi

  # Validate between subject and body
  if [[ $i -eq 1 ]]; then
    if [[ ${#line} -gt 0 ]]; then
      echo -en "${msg_color_red}Subject and body have to be separated by a blank line${msg_color_none} \n"
      exit 1
    fi
  fi

  # Validate body
  if [[ $i -gt 1 ]]; then
    if [[ ${#line} -gt 72 ]]; then
      echo -en "${msg_color_red}Body lines should not exceed 72 characters${msg_color_none} \n"
      exit 1
    fi
  fi

  i=$((i + 1))
done < "$1"

exit 0
